In [1]:
import os
import json
import sys
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
sys.path.append('../../src')
import DISData as DD
import time

In [2]:
doUT = DD.SQL()

host:  192.168.0.201
user:  diadmin
password:  ········

SQL connection done

In [3]:
query1_1 = (f'''CREATE TABLE IF NOT EXISTS preventing_drowsy_semicontrolled_crop_info(
            id INT PRIMARY KEY AUTO_INCREMENT,
            img_name VARCHAR(255) NOT NULL,
            img_dir VARCHAR(255) NOT NULL,
            img_format VARCHAR(10) NOT NULL,
            img_width INT NOT NULL,
            img_height INT NOT NULL,
            color_space VARCHAR(10) NOT NULL,
            label_name VARCHAR(255) NOT NULL,
            label_dir VARCHAR(1000) NOT NULL,
            label_format VARCHAR(10) NOT NULL,
            occupant_id VARCHAR(10) NOT NULL,
            occupant_sex VARCHAR(20) NOT NULL,
            occupant_age VARCHAR(20) NOT NULL,
            accessory VARCHAR(20));''')

In [4]:
query1_2 = (f'''CREATE TABLE IF NOT EXISTS preventing_drowsy_semicontrolled_landmark_info(
            id INT PRIMARY KEY AUTO_INCREMENT,
            img_name VARCHAR(255) NOT NULL,
            img_dir VARCHAR(255) NOT NULL,
            img_format VARCHAR(10) NOT NULL,
            img_width INT NOT NULL,
            img_height INT NOT NULL,
            color_space VARCHAR(10) NOT NULL,
            label_name VARCHAR(255) NOT NULL,
            label_dir VARCHAR(1000) NOT NULL,
            label_format VARCHAR(10) NOT NULL,
            occupant_id VARCHAR(10) NOT NULL,
            occupant_sex VARCHAR(20) NOT NULL,
            occupant_age VARCHAR(20) NOT NULL,
            accessory VARCHAR(20),
            landmark VARCHAR(1000));''')

In [5]:
query2_1 = (f'''INSERT INTO preventing_drowsy_semicontrolled_landmark_info 
        (img_name, img_dir, img_format, img_width, img_height, color_space,
        label_name, label_dir, label_format,
        occupant_id, occupant_sex, occupant_age, accessory, landmark)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)''')
query2_2 = (f'''INSERT INTO preventing_drowsy_semicontrolled_crop_info 
        (img_name, img_dir, img_format, img_width, img_height, color_space,
        label_name, label_dir, label_format,
        occupant_id, occupant_sex, occupant_age, accessory, project_id)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)''')

In [6]:
labels = {1:'M', 2:'F'}

In [7]:
try:
    doUT.create_table(query1_1)
except Exception as e:
    print(f"Error during table creation: {e}")
try:
    doUT.create_table(query1_2)
except Exception as e:
    print(f"Error during table creation: {e}")

create table done
create table done

In [20]:
value_list2 = []
error_list = []

label_path = 'Z:\\preventing_drowsy_semicontrolled\\data\\IR\\labeldata'
img_path = 'Z:\\preventing_drowsy_semicontrolled\\data\\IR\\rawdata'
label_lists = os.listdir(label_path)

for cnt, label_list in enumerate(label_lists):
    label_files = os.listdir(os.path.join(label_path,label_list))
    total_cnt = len(label_lists)
    color_space = 'RGB'
    for label_file in label_files:
    
        label_dir = os.path.join(label_path,label_list,label_file)
        label_name, label_format = os.path.splitext(os.path.basename(label_file))
        label_format = label_format.replace('.','')

        # print(label_dir)
        # print(img_dir)
        img_dir = label_dir.replace('json','jpg').replace('label','raw')
        # print(img_load)

        img_name, img_format = os.path.splitext(os.path.basename(img_dir))
        img_format = img_format.replace('.','')

        # print(img_dir)
        img = cv2.imread(img_dir)
        img_width = img.shape[0]
        img_height = img.shape[1]
        with open(label_dir,'r',encoding='utf-8') as f:
            config = json.load(f)
            
        occupant_id = config['UserInfo']['ID']
        occupant_sex = labels[config['UserInfo']['Gender']]
        occupant_age = config['UserInfo']['Age']

        accessories = config['Accessory']

        accessory = []



        for i in accessories:
            if accessories[i] == True:
                accessory.append(i)
        accessory = ",".join(map(str,accessory))

        if accessory == []:
            accessory = 'NULL'

        img_points = config['ObjectInfo']['KeyPoints']['Points']
        points = []
        for cnt, point in enumerate(img_points[:136]):
            if cnt % 2 == 0:
                x = int(float(point))
            else :
                y = int(float(point))
                points.append((x,y))
        landmark = ",".join(map(str, [(int(float(x)), int(float(y))) for x,y in points]))
        img_dir = img_dir.replace('Z:','DataBase')
        label_dir = label_dir.replace('Z:','DataBase')

        values2 = (img_name, img_dir, img_format, img_width, img_height, color_space, 
                    label_name, label_dir, label_format,
                    occupant_id, occupant_sex, occupant_age, accessory, landmark)
        
        value_list2.append(values2)

        if len(value_list2) >= 500:
            doUT.insert_dataset_values(query2_1, value_list2)
            value_list2 = []
            print(f'{num} / {len(label_ids)}')

doUT.insert_dataset_values(query2_1, value_list2)
# print(value_list2)
print('done')

insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 500 done
0 / 94
insert 499 done
done